branch-defaults:
  default:
    environment: testmaxfischer
    group_suffix: null
global:
  application_name: testmaxfischer2
  branch: null
  default_ec2_keyname: royalstar
  default_platform: Python 2.7
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
